services:
  db:
    image: mysql:8.0.42
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      # MYSQL_USER: ${DB_USER}
      # MYSQL_PASSWORD: ${DB_PASS}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "${DB_PORT}:3306"
    volumes:
      # The Persistence Magic
      # Maps "./mysql_data" on your PC to the MySQL storage folder in the container
      - ./mysql_data:/var/lib/mysql
    networks:
      - my_network

  backend:
    build: ./backend
    image: social-backend
    container_name: social-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
    ports:
      - "${BE_PORT}:8080"
    networks:
      - my_network
  frontend:
    build: ./frontend
    image: social-frontend
    container_name: social-frontend
    ports:
      - "${FE_PORT}:3000"
    depends_on:
      - backend
    networks:
      - my_network
networks:
  my_network:
    external: false
